HOST: http://api.1x.sk/

--- 1X public API ---
---

Společnost 1X je registrátorem domén. Prostřednictvím API nabízí služby koncovým zákazníkům i subregistrátorům, kteří jednají jménem svých zákazníků.

## Koncoví zákazníci

Koncový zákazník si zaregistruje účet (kontakt), pomocí kterého se přihlašuje do systému 1X a registruje pod ním domény. Údaje z kontaktu jsou automaticky propisovány do jednotlivých registrů, kde dochází k automatickému zakládání kontaktl při první registraci domény. Aktualizace údajů kontaktu (např. změna adresy zákazníka) se automaticky propisuje do všech registrů.

## Subregistrátoři

Subregistrátor může obdobně registrovat pod svým účtem i kontakty svých zákazníků. Pro pohodlné napojení do svého systému si může každý kontakt nějak pojmenovat nebo mu přidělit uuid. Pokud není uuid součástí požadavku na registraci kontaktu, systém 1X vygeneruje nové a poskytne ho v odpovědi na žádost o registraci kontaktu. Kontakt lze přejmenovávat, uuid je neměnné. Při registraci domény lze jako identifikátor osoby držitele, administrativního nebo technického kontaktu uvádět identifikátor kontaktu z registru, identifikátor (název) kontaktu 1X nebo právě uuid.

Požadavky, které posílá registrátor jménem svého zákazníka, by měl posílat jen se souhlasem zákazníka. Souhlas může být zajištěn smluvně nebo ho může vyžadovat explicitně při každém zadání požadavku. Subregistrátor také musí mít od zákazníka souhlas s pravidly registrace a řešení sporů (ADR) příslušných registrů domén.

Pokud dojde ke zrušení vztahu subregistrátora a zákazníka, využije subregistrátor API volání, kterým své zmocnění zruší i v systému 1X. S doménami pak nadále může nakládat již jen zákazník, ten může ale subregistrátora opět zmocnit.

## Požadavky

Požadavky se posílají protokolem JSON s autorizací HTTP Auth a s uvedením Content Type a Accept hlaviček se zasílají metodou POST na příslušné URL, informační zdroje jsou dotazovány metodou GET.

## Vyřizování požadavků

Každý požadavek je uložen, je mu přiděleno číslo a je možné se ptát na stav jeho zpracování. (ze zpracování, zpracováno, zpracování selhalo). Ke každému požadavku také může být připojeno více zpráv informujících o detailu zpracování. Zprávy mají lidsky čitelnou část a strojově zpracovatelný kód odpovědi.

Většina služeb umožňuje podání hromadného požadavku (registrace více domén jedním API voláním, hromadné převody domén, hromadné změny v doménách).

Odpovědí na jednotné i hromadné požadavky je vždy objednávka. Objednávku je možné založit také přímým API voláním a do takové objednávky je možné sdružit i různé druhy požadavků.

## Hlášení chyb

Návrhy na úpravy API, opravy chyb a další komentáře je možné vkládat na https://github.com/kubicek/1x_api/issues. Podpora k API je poskytována na adrese podpora@xnet.cz.
---
--
Domains
Tato část popisuje práci s doménami
--

Detail domény

Parametry:

* **fqdnu** - název domény s tečkou (.) nahrazenou podtržítkem (_)

GET /domains/{fqdnu}
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "1x.sk",
      "status": "active",
      "expires_on": "2011-08-28",
      "account": {
        "id": "e639a103-048a-4aee-ac68-80d9799b2fc0",
        "handle": "META:2"
      },
      "_links": {
        "self": {
          "href": "/domains/1x_sk"
        }
      }
    }
  ]
}

Služba pro ověření dostupnosti domény.

Parametry:

* **name** - jméno domény

POST /domains/check
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/4f1a21ae-9cfb-455e-a9e2-15572d3a4cb0
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "domena.cz",
      "status": "pending",
      "expires_on": null,
      "_links": {
        "self": {
          "href": "/domains/domena_cz"
        }
      },
      "request": {
        "id": "5da7065f-f982-4280-ae9f-3b791c6ae93c",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/5da7065f-f982-4280-ae9f-3b791c6ae93c"
          }
        },
        "request_type": "check",
        "responses": [],
        "content": null
      }
    }
  ]
}

Služba pro registraci nového doménového jména.

Parametry:

* **name** - jméno domény
* **registrant** - identifikátor kontaktu držitele
* **period** - počet let
* **dns_zone_template_id** - identifikátor šablony DNS záznamů (deleguje na náš NSSET)
* **nsset** - identifikátor sady jmenných serverů (pouze pro cz domény)
* **nameservers** - jména jmenných serverů (pro ostatní domény)
* **admins** - administrativní kontakty domény
* **keyset** - identifikátor sady klíčů
* **authorization_key** - autorizační klíč domény

POST /domains/register
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "period": "1",
      "registrant": "DRZITEL",
      "nsset": "KRAXNET",
      "dns_zone_template_id": "1",
      "keyset": "KEYSET",
      "authorization_key": "1234abcd",
      "admins": [
        "ADMIN1",
        "ADMIN2"
      ]
    },
    {
      "name": "domain.com",
      "period": "1",
      "registrant": "HOLDER",
      "nameservers": [
        "ns.kraxnet.cz",
        "ns.kraxnet.com"
      ],
      "dns_zone_template_id": "1"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/a1e168d0-5953-408b-8b00-80de8a318937
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "domena.cz",
      "status": "pending",
      "expires_on": null,
      "_links": {
        "self": {
          "href": "/domains/domena_cz"
        }
      },
      "request": {
        "id": "78b53bd1-34e1-40a2-b111-5648bb93f46c",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/78b53bd1-34e1-40a2-b111-5648bb93f46c"
          }
        },
        "request_type": "register",
        "responses": [],
        "content": {
          "period": "1",
          "registrant": "DRZITEL",
          "nsset": "KRAXNET",
          "dns_zone_template_id": "1",
          "keyset": "KEYSET",
          "authorization_key": "1234abcd",
          "admins": [
            "ADMIN1",
            "ADMIN2"
          ]
        }
      }
    },
    {
      "name": "domain.com",
      "status": "pending",
      "expires_on": null,
      "_links": {
        "self": {
          "href": "/domains/domain_com"
        }
      },
      "request": {
        "id": "31b7d7a9-c7e7-4353-a0ca-e30cd096581e",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/31b7d7a9-c7e7-4353-a0ca-e30cd096581e"
          }
        },
        "request_type": "register",
        "responses": [],
        "content": {
          "period": "1",
          "registrant": "HOLDER",
          "nameservers": [
            "ns.kraxnet.cz",
            "ns.kraxnet.com"
          ],
          "dns_zone_template_id": "1"
        }
      }
    }
  ]
}

Služba pro změnu registrátora domény na 1X.

Parametry:

* **name** - jméno domény
* **authorization_key** - autorizační klíč pro převod domény

POST /domains/transfer
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "authorization_key": "1234abcd"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/5d722770-c4ad-4d47-acdd-324dc7e216e5
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "domena.cz",
      "status": "pending",
      "expires_on": null,
      "_links": {
        "self": {
          "href": "/domains/domena_cz"
        }
      },
      "request": {
        "id": "3f9917c4-0e94-4a2a-a550-47aadc349217",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/3f9917c4-0e94-4a2a-a550-47aadc349217"
          }
        },
        "request_type": "transfer",
        "responses": [],
        "content": {
          "authorization_key": "1234abcd"
        }
      }
    }
  ]
}

Služba pro prodloužení registrace doménového jména.

Parametry:

* **name** - jméno domény
* **current_expiration_date** - datum expirace domény
* **period** - počet let

POST /domains/renew
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "period": "1",
      "current_expiration_date": "2014-06-06"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/34200f94-01a6-40ce-8a7b-770c039b8794
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "domena.cz",
      "status": "active",
      "expires_on": "2014-06-06",
      "_links": {
        "self": {
          "href": "/domains/domena_cz"
        }
      },
      "request": {
        "id": "0e445d82-3cd3-4f03-909c-e884e620c9ad",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/0e445d82-3cd3-4f03-909c-e884e620c9ad"
          }
        },
        "request_type": "renew",
        "responses": [],
        "content": {
          "period": "1",
          "current_expiration_date": "2014-06-06"
        }
      }
    }
  ]
}

Služba pro redelegaci domény na jiné jmenné servery.

Parametry:

* **name** - jméno domény
* **dns_zone_template_id** - identifikátor šablony DNS záznamů (deleguje na náš NSSET)
* **nsset** - identifikátor sady jmenných serverů (pouze pro cz domény)
* **nameservers** - jména jmenných serverů (pro ostatní domény)

POST /domains/change_dns
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "nsset": "KRAXNET",
      "dns_zone_template_id": "1"
    },
    {
      "name": "domain.com",
      "nameservers": [
        "ns.kraxnet.cz",
        "ns.kraxnet.com"
      ],
      "dns_zone_template_id": "1"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/d90993ab-0b33-4359-9ad2-4afeb6489854
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "domena.cz",
      "status": "active",
      "expires_on": "2014-06-06",
      "_links": {
        "self": {
          "href": "/domains/domena_cz"
        }
      },
      "request": {
        "id": "de55db74-6779-4eda-9af9-3048be5a9bc5",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/de55db74-6779-4eda-9af9-3048be5a9bc5"
          }
        },
        "request_type": "change_dns",
        "responses": [],
        "content": {
          "nsset": "KRAXNET",
          "dns_zone_template_id": "1"
        }
      }
    },
    {
      "name": "domain.com",
      "status": "pending",
      "expires_on": null,
      "_links": {
        "self": {
          "href": "/domains/domain_com"
        }
      },
      "request": {
        "id": "ffdb5546-fb41-4b8f-b103-564c88f93b56",
        "status": "failed",
        "last_response": {
          "id": "63bcfe41-ffa1-415f-a4c1-55aa23120cf7",
          "code": "not_authorized",
          "message": "Not authorized"
        },
        "_links": {
          "self": {
            "href": "/requests/ffdb5546-fb41-4b8f-b103-564c88f93b56"
          }
        },
        "request_type": "change_dns",
        "responses": [
          {
            "id": "63bcfe41-ffa1-415f-a4c1-55aa23120cf7",
            "code": "not_authorized",
            "message": "Not authorized"
          }
        ],
        "content": {
          "nameservers": [
            "ns.kraxnet.cz",
            "ns.kraxnet.com"
          ],
          "dns_zone_template_id": "1"
        }
      }
    }
  ]
}

Služba pro změnu držitele doménového jména.

Parametry:

* **name** - jméno domény
* **registrant** - identifikátor kontaktu nového držitele

POST /domains/registrant_change
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "registrant": "NOVY_DRZITEL"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/8ac11a0d-fe49-468d-a735-fc48d208d555
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "domena.cz",
      "status": "active",
      "expires_on": "2014-06-06",
      "_links": {
        "self": {
          "href": "/domains/domena_cz"
        }
      },
      "request": {
        "id": "0a642515-83ff-4d41-a798-fc2d97da7ae8",
        "status": "waiting_for_authorization",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/0a642515-83ff-4d41-a798-fc2d97da7ae8"
          }
        },
        "request_type": "registrant_change",
        "responses": [],
        "content": {
          "registrant": "NOVY_DRZITEL"
        }
      }
    }
  ]
}

Služba pro obecnou změnu údajů domény. Neslouží ke změně držitele domény a změně DNS.

Parametry:

* **name** - jméno domény
* **admins** - administrativní kontakty domény
* **keyset** - identifikátor sady klíčů
* **authorization_key** - autorizační klíč domény

POST /domains/update
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "keyset": "KEYSET",
      "authorization_key": "1234abcd",
      "admins": [
        "ADMIN1",
        "ADMIN2"
      ]
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/12200a80-d64f-41d0-ad86-d9a082d92a91
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "domena.cz",
      "status": "active",
      "expires_on": "2014-06-06",
      "_links": {
        "self": {
          "href": "/domains/domena_cz"
        }
      },
      "request": {
        "id": "fcb3ca90-76e5-4785-9633-ce3f8205d50a",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/fcb3ca90-76e5-4785-9633-ce3f8205d50a"
          }
        },
        "request_type": "update",
        "responses": [],
        "content": {
          "keyset": "KEYSET",
          "authorization_key": "1234abcd",
          "admins": [
            "ADMIN1",
            "ADMIN2"
          ]
        }
      }
    }
  ]
}

Služba pro odpojení domény z účtu subregistrátora (zánik vztahu se zákazníkem).

Parametry:

* **name** - jméno domény

POST /domains/release
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/3395b5a3-de8e-4d5b-a7eb-85ea2b0a596c
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "domena.cz",
      "status": "active",
      "expires_on": "2014-06-06",
      "_links": {
        "self": {
          "href": "/domains/domena_cz"
        }
      },
      "request": {
        "id": "bb5fd4d8-4d58-4cd1-a1dc-ac28e0426b40",
        "status": "successful",
        "last_response": {
          "id": "b7c24166-0d3c-4e3f-9b56-e51465f84757",
          "code": "domain_removed",
          "message": "Domain was removed from account"
        },
        "_links": {
          "self": {
            "href": "/requests/bb5fd4d8-4d58-4cd1-a1dc-ac28e0426b40"
          }
        },
        "request_type": "release",
        "responses": [
          {
            "id": "b7c24166-0d3c-4e3f-9b56-e51465f84757",
            "code": "domain_removed",
            "message": "Domain was removed from account"
          }
        ],
        "content": null
      }
    }
  ]
}

Služba pro získání seznamu všech domén.

GET /domains
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "1x.sk",
      "status": "active",
      "expires_on": "2011-08-28",
      "account": {
        "id": "353040c1-ad96-42b0-82a0-3fc9011bdeb9",
        "handle": "META:11"
      },
      "_links": {
        "self": {
          "href": "/domains/1x_sk"
        }
      }
    },
    {
      "name": "kraxnet.cz",
      "status": "active",
      "expires_on": "2011-08-25",
      "account": {
        "id": "353040c1-ad96-42b0-82a0-3fc9011bdeb9",
        "handle": "META:11"
      },
      "_links": {
        "self": {
          "href": "/domains/kraxnet_cz"
        }
      }
    }
  ]
}

Služba pro získání seznamu expirujících domén.

GET /domains/expiring
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "kraxnet.cz",
      "status": "active",
      "expires_on": "2011-08-25",
      "account": {
        "id": "8f0bcf92-2f5c-48e8-afa7-bef335ad37f0",
        "handle": "META:12"
      },
      "_links": {
        "self": {
          "href": "/domains/kraxnet_cz"
        }
      }
    },
    {
      "name": "1x.sk",
      "status": "active",
      "expires_on": "2011-08-28",
      "account": {
        "id": "8f0bcf92-2f5c-48e8-afa7-bef335ad37f0",
        "handle": "META:12"
      },
      "_links": {
        "self": {
          "href": "/domains/1x_sk"
        }
      }
    }
  ]
}

--
Contacts
Tato část popisuje práci s kontakty
--

Detail kontaktu

Parametry:

* **id** - handle nebo UUID kontaktu

GET /contacts/{id}
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "contacts": [
    {
      "id": "4f6e55ef-ba36-4c39-a101-242a0c003611",
      "handle": "META:TEST",
      "organization_name": null,
      "name_prefix": null,
      "first_name": "Jan",
      "last_name": "Novák",
      "name_suffix": null,
      "identification_number": null,
      "vat_id": null,
      "email": "user@test.cz",
      "phone": "800123456",
      "fax": null,
      "street": [
        "Ulice 123"
      ],
      "city": "Město 5",
      "zip": "12345",
      "country_code": "CZ",
      "state": null,
      "new_cz_nic_handle": null,
      "cz_nic_notify_email": null,
      "cz_nic_hide": [],
      "tld_handles": {
        "cz": "TEST"
      },
      "_links": {
        "self": {
          "href": "/contacts/META:TEST"
        }
      }
    }
  ]
}

Služba pro vytvoření nového kontaktu.

Parametry:

* **handle** - identifikátor kontaktu
* **organization_name** - firma
* **name_prefix** - titul před jménem
* **first_name** - jméno
* **last_name** - příjmení
* **name_suffix** - titul za jménem
* **identification_number** - IČ
* **vat_id** - DIČ
* **email** - e-mail
* **phone** - telefon
* **fax** - fax
* **street** - ulice, číslo popisné
* **city** - město
* **zip** - poštovní směrovací číslo
* **country_code** - kód státu
* **state** - region
* **new_cz_nic_handle** - identifikátor nového kontaktu CZ.NIC
* **cz_nic_notify_email** - e-mail pro oznámení CZ.NIC
* **cz_nic_hide** - skryté údaje v registru CZ.NIC
* **id** - universally unique identifier (UUID)

POST /contacts/register
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "contacts": [
    {
      "id": "4f6e55ef-ba36-4c39-a101-242a0c003611",
      "handle": "META:TEST",
      "organization_name": "Test a.s.",
      "name_prefix": "Ing.",
      "first_name": "Jan",
      "last_name": "Novák",
      "name_suffix": "CSc.",
      "identification_number": "12345678",
      "vat_id": "CZ12345678",
      "email": "novak@nic.cz",
      "phone": "+420.800123456",
      "fax": "+420.800778899",
      "street": "U testu 5",
      "city": "Testov 6",
      "zip": "12310",
      "country_code": "CZ",
      "state": "",
      "new_cz_nic_handle": "jnovak",
      "cz_nic_notify_email": "jan.novak@nic.cz",
      "cz_nic_hide": [
        "ident",
        "vat",
        "email",
        "phone",
        "fax",
        "notify_email"
      ]
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/ee4cf616-9ae4-44e2-a22b-f1b4b8f0b0f3
< Content-Type: application/json; charset=utf-8
{
  "contacts": [
    {
      "id": "4f6e55ef-ba36-4c39-a101-242a0c003611",
      "handle": "META:TEST",
      "organization_name": "Test a.s.",
      "name_prefix": "Ing.",
      "first_name": "Jan",
      "last_name": "Novák",
      "name_suffix": "CSc.",
      "identification_number": "12345678",
      "vat_id": "CZ12345678",
      "email": "novak@nic.cz",
      "phone": "+420.800123456",
      "fax": "+420.800778899",
      "street": [
        "U testu 5"
      ],
      "city": "Testov 6",
      "zip": "12310",
      "country_code": "CZ",
      "state": null,
      "new_cz_nic_handle": "jnovak",
      "cz_nic_notify_email": "jan.novak@nic.cz",
      "cz_nic_hide": [
        "ident",
        "vat",
        "email",
        "phone",
        "fax",
        "notify_email"
      ],
      "_links": {
        "self": {
          "href": "/contacts/META:TEST"
        }
      },
      "request": {
        "id": "e01309f4-3e92-4417-9efa-bfd931c08e44",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/e01309f4-3e92-4417-9efa-bfd931c08e44"
          }
        },
        "request_type": "register",
        "responses": [],
        "content": {
          "id": "4f6e55ef-ba36-4c39-a101-242a0c003611",
          "organization_name": "Test a.s.",
          "name_prefix": "Ing.",
          "first_name": "Jan",
          "last_name": "Novák",
          "name_suffix": "CSc.",
          "identification_number": "12345678",
          "vat_id": "CZ12345678",
          "email": "novak@nic.cz",
          "phone": "+420.800123456",
          "fax": "+420.800778899",
          "street": "U testu 5",
          "city": "Testov 6",
          "zip": "12310",
          "country_code": "CZ",
          "new_cz_nic_handle": "jnovak",
          "cz_nic_notify_email": "jan.novak@nic.cz",
          "cz_nic_hide": [
            "ident",
            "vat",
            "email",
            "phone",
            "fax",
            "notify_email"
          ]
        }
      }
    }
  ]
}

Služba pro změnu kontaktu.

Parametry:

* **handle** - identifikátor kontaktu
* **organization_name** - firma
* **name_prefix** - titul před jménem
* **first_name** - jméno
* **last_name** - příjmení
* **name_suffix** - titul za jménem
* **identification_number** - IČ
* **vat_id** - DIČ
* **email** - e-mail
* **phone** - telefon
* **fax** - fax
* **street** - ulice, číslo popisné
* **city** - město
* **zip** - poštovní směrovací číslo
* **country_code** - kód státu
* **state** - region
* **new_cz_nic_handle** - identifikátor nového kontaktu CZ.NIC
* **cz_nic_notify_email** - e-mail pro oznámení CZ.NIC
* **cz_nic_hide** - skryté údaje v registru CZ.NIC
* **id** - universally unique identifier (UUID)

POST /contacts/update
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "contacts": [
    {
      "id": "4f6e55ef-ba36-4c39-a101-242a0c003611",
      "handle": "META:TEST",
      "organization_name": "Test a.s.",
      "name_prefix": "Ing.",
      "first_name": "Jan",
      "last_name": "Novák",
      "name_suffix": "CSc.",
      "identification_number": "12345678",
      "vat_id": "CZ12345678",
      "email": "novak@nic.cz",
      "phone": "+420.800123456",
      "fax": "+420.800778899",
      "street": "U testu 5",
      "city": "Testov 6",
      "zip": "12310",
      "country_code": "CZ",
      "state": "",
      "new_cz_nic_handle": "jnovak",
      "cz_nic_notify_email": "jan.novak@nic.cz",
      "cz_nic_hide": [
        "ident",
        "vat",
        "email",
        "phone",
        "fax",
        "notify_email"
      ]
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/bfdce8f8-a566-4e98-9f5c-dd4819630a6d
< Content-Type: application/json; charset=utf-8
{
  "contacts": [
    {
      "id": "4f6e55ef-ba36-4c39-a101-242a0c003611",
      "handle": "META:TEST",
      "organization_name": "Test a.s.",
      "name_prefix": "Ing.",
      "first_name": "Jan",
      "last_name": "Novák",
      "name_suffix": "CSc.",
      "identification_number": "12345678",
      "vat_id": "CZ12345678",
      "email": "novak@nic.cz",
      "phone": "+420.800123456",
      "fax": "+420.800778899",
      "street": [
        "U testu 5"
      ],
      "city": "Testov 6",
      "zip": "12310",
      "country_code": "CZ",
      "state": null,
      "new_cz_nic_handle": "jnovak",
      "cz_nic_notify_email": "jan.novak@nic.cz",
      "cz_nic_hide": [
        "ident",
        "vat",
        "email",
        "phone",
        "fax",
        "notify_email"
      ],
      "_links": {
        "self": {
          "href": "/contacts/META:TEST"
        }
      },
      "request": {
        "id": "8a05217f-ea71-4c0c-b0d8-ba7bc351b7de",
        "status": "successful",
        "last_response": {
          "id": "8a5761c9-851c-4c14-aa65-d2daccefcba7",
          "code": "domain_available",
          "message": "Contact was updated"
        },
        "_links": {
          "self": {
            "href": "/requests/8a05217f-ea71-4c0c-b0d8-ba7bc351b7de"
          }
        },
        "request_type": "update",
        "responses": [
          {
            "id": "8a5761c9-851c-4c14-aa65-d2daccefcba7",
            "code": "domain_available",
            "message": "Contact was updated"
          }
        ],
        "content": {
          "id": "4f6e55ef-ba36-4c39-a101-242a0c003611",
          "organization_name": "Test a.s.",
          "name_prefix": "Ing.",
          "first_name": "Jan",
          "last_name": "Novák",
          "name_suffix": "CSc.",
          "identification_number": "12345678",
          "vat_id": "CZ12345678",
          "email": "novak@nic.cz",
          "phone": "+420.800123456",
          "fax": "+420.800778899",
          "street": "U testu 5",
          "city": "Testov 6",
          "zip": "12310",
          "country_code": "CZ",
          "new_cz_nic_handle": "jnovak",
          "cz_nic_notify_email": "jan.novak@nic.cz",
          "cz_nic_hide": [
            "ident",
            "vat",
            "email",
            "phone",
            "fax",
            "notify_email"
          ]
        }
      }
    }
  ]
}

Služba pro odebrání kontaktu z účtu.

Parametry:

* **handle** - identifikátor kontaktu
* **id** - universally unique identifier (UUID)

POST /contacts/release
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "contacts": [
    {
      "handle": "META:TEST"
    },
    {
      "id": "4f6e55ef-ba36-4c39-a101-242a0c003611"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/c10c4288-c6fd-4b20-8c4a-af4f77f82767
< Content-Type: application/json; charset=utf-8
{
  "contacts": [
    {
      "id": "4f6e55ef-ba36-4c39-a101-242a0c003611",
      "handle": "META:TEST",
      "organization_name": null,
      "name_prefix": null,
      "first_name": "Jan",
      "last_name": "Novák",
      "name_suffix": null,
      "identification_number": null,
      "vat_id": null,
      "email": "user@test.cz",
      "phone": "800123456",
      "fax": null,
      "street": [
        "Ulice 123"
      ],
      "city": "Město 5",
      "zip": "12345",
      "country_code": "CZ",
      "state": null,
      "new_cz_nic_handle": null,
      "cz_nic_notify_email": null,
      "cz_nic_hide": [],
      "_links": {
        "self": {
          "href": "/contacts/META:TEST"
        }
      },
      "request": {
        "id": "9e211ea0-89a9-40f1-9271-f34529e045cd",
        "status": "failed",
        "last_response": {
          "id": "dbf5489c-a36a-46aa-927e-c6d249813a2e",
          "code": "contact_not_removed",
          "message": "Contact can not be removed from account"
        },
        "_links": {
          "self": {
            "href": "/requests/9e211ea0-89a9-40f1-9271-f34529e045cd"
          }
        },
        "request_type": "release",
        "responses": [
          {
            "id": "dbf5489c-a36a-46aa-927e-c6d249813a2e",
            "code": "contact_not_removed",
            "message": "Contact can not be removed from account"
          }
        ],
        "content": null
      }
    },
    {
      "id": "4f6e55ef-ba36-4c39-a101-242a0c003611",
      "handle": "META:TEST",
      "organization_name": null,
      "name_prefix": null,
      "first_name": "Jan",
      "last_name": "Novák",
      "name_suffix": null,
      "identification_number": null,
      "vat_id": null,
      "email": "user@test.cz",
      "phone": "800123456",
      "fax": null,
      "street": [
        "Ulice 123"
      ],
      "city": "Město 5",
      "zip": "12345",
      "country_code": "CZ",
      "state": null,
      "new_cz_nic_handle": null,
      "cz_nic_notify_email": null,
      "cz_nic_hide": [],
      "_links": {
        "self": {
          "href": "/contacts/META:TEST"
        }
      },
      "request": {
        "id": "9e211ea0-89a9-40f1-9271-f34529e045cd",
        "status": "failed",
        "last_response": {
          "id": "dbf5489c-a36a-46aa-927e-c6d249813a2e",
          "code": "contact_not_removed",
          "message": "Contact can not be removed from account"
        },
        "_links": {
          "self": {
            "href": "/requests/9e211ea0-89a9-40f1-9271-f34529e045cd"
          }
        },
        "request_type": "release",
        "responses": [
          {
            "id": "dbf5489c-a36a-46aa-927e-c6d249813a2e",
            "code": "contact_not_removed",
            "message": "Contact can not be removed from account"
          }
        ],
        "content": null
      }
    }
  ]
}

--
Nssets
Tato část popisuje práci s nssety
--

Služba pro ověření dostupnosti nssetu.

Parametry:

* **id** - identifikátor nssetu

POST /nssets/check
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "nssets": [
    {
      "id": "NSSET"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/8b0f4312-fa45-431d-ae56-78fba286bd1e
< Content-Type: application/json; charset=utf-8
{
  "nssets": [
    {
      "name": "NSSET",
      "status": "pending",
      "_links": {
        "self": {
          "href": "/nssets/NSSET"
        }
      },
      "request": {
        "id": "eddf8607-bbc7-4bfb-af5d-d97869d22559",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/eddf8607-bbc7-4bfb-af5d-d97869d22559"
          }
        },
        "request_type": "check",
        "responses": [],
        "content": null
      }
    }
  ]
}

Služba pro vytvoření nového nssetu.

Parametry:

* **id** - identifikátor nssetu
* **nameservers** - výčet nameserverů
* **techs** - identifikátory kontaktů oprávněných ke správě nssetu
* **authorization_key** - autorizační klíč NSSETu
* **report_level** - úroveň kontroly

POST /nssets/register
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "nssets": [
    {
      "id": "NSSET",
      "techs": [
        "TECH1",
        "TECH2"
      ],
      "nameservers": [
        {
          "hostname": "ns.kraxnet.cz",
          "addresses": [
            "1.2.3.4"
          ]
        },
        {
          "hostname": "ns.kraxnet.com",
          "addresses": [
            "5.6.7.8",
            "9.10.11.12"
          ]
        }
      ],
      "authorization_key": "1234abcd",
      "report_level": "7"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/a76a4444-9b1e-4e0e-ad15-5c6ce02f0a39
< Content-Type: application/json; charset=utf-8
{
  "nssets": [
    {
      "name": "NSSET",
      "status": "pending",
      "_links": {
        "self": {
          "href": "/nssets/NSSET"
        }
      },
      "request": {
        "id": "959945b9-ecae-4679-87f8-fa42f8896d2c",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/959945b9-ecae-4679-87f8-fa42f8896d2c"
          }
        },
        "request_type": "register",
        "responses": [],
        "content": {
          "techs": [
            "TECH1",
            "TECH2"
          ],
          "nameservers": [
            {
              "hostname": "ns.kraxnet.cz",
              "addresses": [
                "1.2.3.4"
              ]
            },
            {
              "hostname": "ns.kraxnet.com",
              "addresses": [
                "5.6.7.8",
                "9.10.11.12"
              ]
            }
          ],
          "authorization_key": "1234abcd",
          "report_level": "7"
        }
      }
    }
  ]
}

Služba pro aktualizaci nssetu.

Parametry:

* **id** - identifikátor nssetu
* **nameservers** - výčet nameserverů
* **techs** - identifikátory kontaktů oprávněných ke správě nssetu
* **authorization_key** - autorizační klíč NSSETu
* **report_level** - úroveň kontroly

POST /nssets/update
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "nssets": [
    {
      "id": "NSSET",
      "techs": [
        "TECH1",
        "TECH2"
      ],
      "nameservers": [
        {
          "hostname": "ns.kraxnet.cz",
          "addresses": [
            "1.2.3.4"
          ]
        },
        {
          "hostname": "ns.kraxnet.com",
          "addresses": [
            "5.6.7.8",
            "9.10.11.12"
          ]
        }
      ],
      "authorization_key": "1234abcd",
      "report_level": "7"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/d9af0e31-6855-44cd-91ec-5678a63bb573
< Content-Type: application/json; charset=utf-8
{
  "nssets": [
    {
      "name": "NSSET",
      "status": "active",
      "_links": {
        "self": {
          "href": "/nssets/NSSET"
        }
      },
      "request": {
        "id": "465295cd-0857-49d8-a580-e40d5a648b17",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/465295cd-0857-49d8-a580-e40d5a648b17"
          }
        },
        "request_type": "update",
        "responses": [],
        "content": {
          "techs": [
            "TECH1",
            "TECH2"
          ],
          "nameservers": [
            {
              "hostname": "ns.kraxnet.cz",
              "addresses": [
                "1.2.3.4"
              ]
            },
            {
              "hostname": "ns.kraxnet.com",
              "addresses": [
                "5.6.7.8",
                "9.10.11.12"
              ]
            }
          ],
          "authorization_key": "1234abcd",
          "report_level": "7"
        }
      }
    }
  ]
}

Služba pro zrušení nssetu. Pouze pokud není navázán na doménu.

Parametry:

* **id** - identifikátor nssetu

POST /nssets/delete
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "nssets": [
    {
      "id": "NSSET"
    }
  ]
}
< 202
< Location: http://api.1x.sk/orders/9a09884d-e7b9-4245-9431-8da2dc4f5d61
< Content-Type: application/json; charset=utf-8
{
  "nssets": [
    {
      "name": "NSSET",
      "status": "active",
      "_links": {
        "self": {
          "href": "/nssets/NSSET"
        }
      },
      "request": {
        "id": "1376c88e-a511-4ba5-ae47-7fc69426f291",
        "status": "waiting_for_authorization",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/1376c88e-a511-4ba5-ae47-7fc69426f291"
          }
        },
        "request_type": "delete",
        "responses": [],
        "content": null
      }
    }
  ]
}

--
Requests
Tato část popisuje práci s odpověďmi na požadavky
--

Služba pro zjištění aktuálního stavu požadavku.

Parametry:

* **id** - identifikátor požadavku

Hodnoty odpovědi:

* **processing** - požadavek je ve zpracování
* **failed** - požadavek nebyl zpracován kvůli chybě
* **registered** - (pouze pro požadavek na registraci domény, kontaktu, nssetu) - objekt úspěšně zaregistrován
* **transferred** - (pouze pro požadavek na transfer domény, kontaktu, nssetu) - objekt úspěšně převeden
* **available** - (pouze pro požadavek na ověření dostupnosti domény, kontaktu, nssetu) - objekt je volný pro novou registraci
* **unavailable** - (pouze pro požadavek na ověření dostupnosti domény, kontaktu, nssetu) - objekt není volný
* **successful** - požadavek byl úspěšně zpracován

GET /requests/{id}/status
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": "e9b6f461-f259-4e74-b92a-567a4d3c845c",
    "status": "successful",
    "last_response": {
      "id": "7bde848d-2cbb-4984-b19b-63ef599ff5a9",
      "code": "domain_available",
      "message": "Domain is available"
    },
    "_links": {
      "self": {
        "href": "/requests/e9b6f461-f259-4e74-b92a-567a4d3c845c"
      }
    }
  }
}

Služba pro získání obsahu odeslaného požadavku.

Parametry:

* **id** - identifikátor požadavku

GET /requests/{id}
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": "7274b88d-2cec-4998-aea2-3f0c93fced4e",
    "status": "successful",
    "last_response": {
      "id": "204de6b9-afff-4799-9601-4af8443c7f1a",
      "code": "domain_available",
      "message": "Domain is available"
    },
    "_links": {
      "self": {
        "href": "/requests/7274b88d-2cec-4998-aea2-3f0c93fced4e"
      }
    },
    "object_type": "domain",
    "request_type": "check",
    "registry_object_name": "domena.cz",
    "responses": [
      {
        "id": "204de6b9-afff-4799-9601-4af8443c7f1a",
        "code": "domain_available",
        "message": "Domain is available"
      }
    ],
    "content": null
  }
}

--
Account
Tato část popisuje práci se subregistrátorským účtem
--

Zjištění aktuálního stavu kreditu.

GET /account/balance
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "balance": {
    "currency": "CZK",
    "amount": 0.0
  }
}

--
Order
Tato část popisuje zadávání objednávek s více požadavky
--

Služba pro zadání objednávky s více požadavky naráz.

Základní parametry jednotlivých požadavků:

* **request_type** - typ požadavku
* **object_type** - typ objektu, kterého se požadavek týká
* **name** - název objektu, které se požadavek týká (pouze pro domény)
* **id** - identifikátor objektu, kterého se požadavek týká (pro ostatní objekty)

Další parametry jsou shodné jako u příslušného typu requestu - viz výše.

Povolené hodnoty **object_type**:

* domain
* contact
* nsset
* keyset

Povolené hodnoty **request_type**:

* check
* register
* update
* authinfo
* transfer

Pro domény navíc:

* renew
* change_dns
* registrant_change

Pro ostatní objekty navíc:

* delete

POST /orders
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "requests": [
    {
      "request_type": "check",
      "object_type": "domain",
      "name": "domena.cz"
    },
    {
      "request_type": "check",
      "object_type": "domain",
      "name": "domena2.cz"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "order": {
    "id": "3e3368d9-5b5f-46a4-b317-5e209e78c687",
    "created_at": "2014-10-31T16:22:12+01:00",
    "requests": [
      {
        "id": "1d83e322-f578-480b-98c5-05c66db74a56",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/1d83e322-f578-480b-98c5-05c66db74a56"
          }
        },
        "object_type": "domain",
        "request_type": "check",
        "registry_object_name": "domena.cz",
        "responses": [],
        "content": null
      },
      {
        "id": "6ce8f9ae-67ae-46ba-8683-6c7506b71cc3",
        "status": "processing",
        "last_response": null,
        "_links": {
          "self": {
            "href": "/requests/6ce8f9ae-67ae-46ba-8683-6c7506b71cc3"
          }
        },
        "object_type": "domain",
        "request_type": "check",
        "registry_object_name": "domena2.cz",
        "responses": [],
        "content": null
      }
    ],
    "_links": {
      "self": {
        "href": "/orders/3e3368d9-5b5f-46a4-b317-5e209e78c687"
      }
    }
  }
}
