HOST: http://api.1x.sk/

--- 1X public API ---
---
## Zabezpečení

Pro úspěšné volání funkce API je potřeba zaslat přidělené uživatelské jméno a heslo prostřednictvím HTTP Basic Auth.

## Požadavky

Požadavky se zasílají metodou POST na příslušné URL, informační zdroje jsou dotazovány metodou GET.

## Vyřizování požadavků

Systém každý přijatý požadavek ihned uloží a v odpovědi odešle přidělený unikátní identifikátor. Klient nečeká na odpověď o vyřízení a může odesílat další požadavky. Kdykoliv se pak může pomocí API volání dotázat na aktuální stav vyřizování požadavku. Převážně z tohoto důvodu jsou implementované odpovědi ve formátu JSON, kdy v klientské aplikaci je možné na pozadí např. pomocí JavaScriptu průběžně dotazovat server na stav vyřizování požadavků a tento v reálném čase v aplikaci zobrazovat. Tento způsob komunikace odstraňuje i problémy při nedostupnosti registrů nebo prodlevou v jejich odpovědích. Klienta zasílající požadavek neblokujeme a jeho požadavek zpracujeme, jakmile to bude možné.
---
--
Domains
Tato část popisuje práci s doménami
--

Detail domény

Parametry:

* **fqdnu** - název domény s tečkou (.) nahrazenou podtržítkem (_)

GET /domains/{fqdnu}
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "1x.sk",
      "status": "active",
      "expires_on": "2011-08-28",
      "account": "META:2",
      "_links": {
        "self": {
          "href": "/domains/1x_sk"
        }
      }
    }
  ]
}

Služba pro ověření dostupnosti domény.

Parametry:

* **name** - jméno domény

POST /domains/check
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190963,
    "registry_object_name": "domena.cz",
    "object_type": "domain",
    "content": null,
    "status": "processing",
    "request_type": "check"
  }
}

Služba pro registraci nového doménového jména.

Parametry:

* **name** - jméno domény
* **registrant** - identifikátor kontaktu držitele
* **period** - počet let
* **dns_zone_template_id** - identifikátor šablony DNS záznamů (deleguje na náš NSSET)
* **nsset** - identifikátor sady jmenných serverů (pouze pro cz domény)
* **nameservers** - jména jmenných serverů (pro ostatní domény)
* **admins** - administrativní kontakty domény
* **keyset** - identifikátor sady klíčů
* **authorization_key** - autorizační klíč domény

POST /domains/register
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "period": "1",
      "registrant": "DRZITEL",
      "nsset": "KRAXNET",
      "dns_zone_template_id": "1",
      "keyset": "KEYSET",
      "authorization_key": "1234abcd",
      "admins": [
        {
          "id": "ADMIN1"
        },
        {
          "id": "ADMIN2"
        }
      ]
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190964,
    "registry_object_name": "domena.cz",
    "object_type": "domain",
    "content": {
      "period": "1",
      "registrant": "DRZITEL",
      "nsset": "KRAXNET",
      "dns_zone_template_id": "1",
      "keyset": "KEYSET",
      "authorization_key": "1234abcd",
      "admins": [
        {
          "id": "ADMIN1"
        },
        {
          "id": "ADMIN2"
        }
      ]
    },
    "status": "processing",
    "request_type": "register"
  }
}

Služba pro změnu registrátora domény na 1X.

Parametry:

* **name** - jméno domény
* **authorization_key** - autorizační klíč pro převod domény

POST /domains/transfer
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "authorization_key": "1234abcd"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190965,
    "registry_object_name": "domena.cz",
    "object_type": "domain",
    "content": {
      "authorization_key": "1234abcd"
    },
    "status": "processing",
    "request_type": "transfer"
  }
}

Služba pro prodloužení registrace doménového jména.

Parametry:

* **name** - jméno domény
* **current_expiration_date** - datum expirace domény
* **period** - počet let

POST /domains/renew
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "period": "1",
      "current_expiration_date": "2014-06-06"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190966,
    "registry_object_name": "domena.cz",
    "object_type": "domain",
    "content": {
      "period": "1",
      "current_expiration_date": "2014-06-06"
    },
    "status": "processing",
    "request_type": "renew"
  }
}

Služba pro redelegaci domény na jiné jmenné servery.

Parametry:

* **name** - jméno domény
* **dns_zone_template_id** - identifikátor šablony DNS záznamů (deleguje na náš NSSET)
* **nsset** - identifikátor sady jmenných serverů (pouze pro cz domény)
* **nameservers** - jména jmenných serverů (pro ostatní domény)

POST /domains/change_dns
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "nsset": "KRAXNET",
      "dns_zone_template_id": "1"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190967,
    "registry_object_name": "domena.cz",
    "object_type": "domain",
    "content": {
      "nsset": "KRAXNET",
      "dns_zone_template_id": "1"
    },
    "status": "processing",
    "request_type": "change_dns"
  }
}

Služba pro změnu držitele doménového jména.

Parametry:

* **name** - jméno domény
* **registrant** - identifikátor kontaktu nového držitele

POST /domains/registrant_change
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "registrant": "NOVY_DRZITEL"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190968,
    "registry_object_name": "domena.cz",
    "object_type": "domain",
    "content": {
      "registrant": "NOVY_DRZITEL"
    },
    "status": "waiting_for_authorization",
    "request_type": "registrant_change"
  }
}

Služba pro obecnou změnu údajů domény. Neslouží ke změně držitele domény a změně DNS.

Parametry:

* **name** - jméno domény
* **admins** - administrativní kontakty domény
* **keyset** - identifikátor sady klíčů
* **authorization_key** - autorizační klíč domény

POST /domains/update
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz",
      "keyset": "KEYSET",
      "authorization_key": "1234abcd",
      "admins": [
        {
          "id": "ADMIN1"
        },
        {
          "id": "ADMIN2"
        }
      ]
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190969,
    "registry_object_name": "domena.cz",
    "object_type": "domain",
    "content": {
      "keyset": "KEYSET",
      "authorization_key": "1234abcd",
      "admins": [
        {
          "id": "ADMIN1"
        },
        {
          "id": "ADMIN2"
        }
      ]
    },
    "status": "processing",
    "request_type": "update"
  }
}

Služba pro odpojení domény z účtu subregistrátora (zánik vztahu se zákazníkem).

Parametry:

* **name** - jméno domény

POST /domains/release
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "domains": [
    {
      "name": "domena.cz"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190970,
    "registry_object_name": "domena.cz",
    "object_type": "domain",
    "content": null,
    "status": "successful",
    "request_type": "release"
  }
}

Služba pro získání seznamu všech domén.

GET /domains
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "1x.sk",
      "status": "active",
      "expires_on": "2011-08-28",
      "account": "META:11",
      "_links": {
        "self": {
          "href": "/domains/1x_sk"
        }
      }
    },
    {
      "name": "kraxnet.cz",
      "status": "active",
      "expires_on": "2011-08-25",
      "account": "META:11",
      "_links": {
        "self": {
          "href": "/domains/kraxnet_cz"
        }
      }
    }
  ]
}

Služba pro získání seznamu expirujících domén.

GET /domains/expiring
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "domains": [
    {
      "name": "kraxnet.cz",
      "status": "active",
      "expires_on": "2011-08-25",
      "account": "META:12",
      "_links": {
        "self": {
          "href": "/domains/kraxnet_cz"
        }
      }
    },
    {
      "name": "1x.sk",
      "status": "active",
      "expires_on": "2011-08-28",
      "account": "META:12",
      "_links": {
        "self": {
          "href": "/domains/1x_sk"
        }
      }
    }
  ]
}

--
Contacts
Tato část popisuje práci s kontakty
--

Detail kontaktu

Parametry:

* **id** - handle nebo UUID kontaktu

GET /contacts/{id}
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "contacts": [
    {
      "uuid": "0f095648-2fe7-41d9-931c-590aab0df7bb",
      "handle": "META:TEST",
      "organization_name": null,
      "name_prefix": null,
      "first_name": "Jan",
      "last_name": "Novák",
      "name_suffix": null,
      "identification_number": null,
      "vat_id": null,
      "email": "user@test.cz",
      "phone": "800123456",
      "fax": null,
      "street": [
        "Ulice 123"
      ],
      "city": "Město 5",
      "zip": "12345",
      "country_code": "CZ",
      "state": null,
      "new_cz_nic_handle": null,
      "cz_nic_notify_email": null,
      "cz_nic_hide": [

      ]
    }
  ]
}

Služba pro vytvoření nového kontaktu.

Parametry:

* **handle** - identifikátor kontaktu
* **organization_name** - firma
* **name_prefix** - titul před jménem
* **first_name** - jméno
* **last_name** - příjmení
* **name_suffix** - titul za jménem
* **identification_number** - IČ
* **vat_id** - DIČ
* **email** - e-mail
* **phone** - telefon
* **fax** - fax
* **street** - ulice, číslo popisné
* **city** - město
* **zip** - poštovní směrovací číslo
* **country_code** - kód státu
* **state** - region
* **new_cz_nic_handle** - identifikátor nového kontaktu CZ.NIC
* **cz_nic_notify_email** - e-mail pro oznámení CZ.NIC
* **cz_nic_hide** - skryté údaje v registru CZ.NIC
* **id** - universally unique identifier (UUID)

POST /contacts/register
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "contacts": [
    {
      "handle": "META:TEST",
      "first_name": "Jan",
      "last_name": "Novák",
      "email": "novak@nic.cz",
      "street": "U testu 5",
      "city": "Testov 6",
      "zip": "12310",
      "country_code": "CZ",
      "organization_name": "Test a.s.",
      "phone": "+420.800123456",
      "fax": "+420.800123456",
      "vat_id": "CZ12345678",
      "cz_nic_notify_email": "jan.novak@nic.cz",
      "cz_nic_hide": ["email", "phone", "fax", "ident", "vat", "notify_email"]
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190971,
    "registry_object_name": "META:TEST",
    "object_type": "contact",
    "content": {
      "first_name": "Jan",
      "last_name": "Novák",
      "email": "novak@nic.cz",
      "street": "U testu 5",
      "city": "Testov 6",
      "zip": "12310",
      "country_code": "CZ",
      "organization_name": "Test a.s.",
      "phone": "+420.800123456",
      "fax": "+420.800123456",
      "vat_id": "CZ12345678",
      "cz_nic_notify_email": "jan.novak@nic.cz",
      "cz_nic_hide": [
        "email",
        "phone",
        "fax",
        "ident",
        "vat",
        "notify_email"
      ]
    },
    "status": "successful",
    "request_type": "register"
  }
}

Služba pro změnu kontaktu.

Parametry:

* **handle** - identifikátor kontaktu
* **organization_name** - firma
* **name_prefix** - titul před jménem
* **first_name** - jméno
* **last_name** - příjmení
* **name_suffix** - titul za jménem
* **identification_number** - IČ
* **vat_id** - DIČ
* **email** - e-mail
* **phone** - telefon
* **fax** - fax
* **street** - ulice, číslo popisné
* **city** - město
* **zip** - poštovní směrovací číslo
* **country_code** - kód státu
* **state** - region
* **new_cz_nic_handle** - identifikátor nového kontaktu CZ.NIC
* **cz_nic_notify_email** - e-mail pro oznámení CZ.NIC
* **cz_nic_hide** - skryté údaje v registru CZ.NIC
* **id** - universally unique identifier (UUID)

POST /contacts/update
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "contacts": [
    {
      "handle": "META:TEST",
      "first_name": "Jan",
      "last_name": "Novák",
      "email": "novak@nic.cz",
      "street": "U testu 5",
      "city": "Testov 6",
      "zip": "12310",
      "country_code": "CZ",
      "organization_name": "Test a.s.",
      "phone": "+420.800123456",
      "fax": "+420.800123456",
      "vat_id": "CZ12345678",
      "cz_nic_notify_email": "jan.novak@nic.cz",
      "cz_nic_hide": ["email", "phone", "fax", "ident", "vat", "notify_email"]
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190972,
    "registry_object_name": "META:TEST",
    "object_type": "contact",
    "content": {
      "first_name": "Jan",
      "last_name": "Novák",
      "email": "novak@nic.cz",
      "street": "U testu 5",
      "city": "Testov 6",
      "zip": "12310",
      "country_code": "CZ",
      "organization_name": "Test a.s.",
      "phone": "+420.800123456",
      "fax": "+420.800123456",
      "vat_id": "CZ12345678",
      "cz_nic_notify_email": "jan.novak@nic.cz",
      "cz_nic_hide": [
        "email",
        "phone",
        "fax",
        "ident",
        "vat",
        "notify_email"
      ]
    },
    "status": "failed",
    "request_type": "update"
  }
}

Služba pro odebrání kontaktu z účtu.

Parametry:

* **handle** - identifikátor kontaktu
* **id** - universally unique identifier (UUID)

POST /contacts/release
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "contacts": [
    {
      "handle": "META:TEST"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190973,
    "registry_object_name": "META:TEST",
    "object_type": "contact",
    "content": null,
    "status": "failed",
    "request_type": "release"
  }
}

--
Nssets
Tato část popisuje práci s nssety
--

Služba pro ověření dostupnosti nssetu.

Parametry:

* **id** - identifikátor nssetu

POST /nssets/check
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "nssets": [
    {
      "id": "NSSET"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190974,
    "registry_object_name": "NSSET",
    "object_type": "nsset",
    "content": null,
    "status": "processing",
    "request_type": "check"
  }
}

Služba pro vytvoření nového nssetu.

Parametry:

* **id** - identifikátor nssetu
* **nameservers** - výčet nameserverů
* **techs** - identifikátory kontaktů oprávněných ke správě nssetu
* **authorization_key** - autorizační klíč NSSETu
* **report_level** - úroveň kontroly

POST /nssets/register
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "nssets": [
    {
      "id": "NSSET",
      "techs": [
        {
          "id": "TECH1"
        },
        {
          "id": "TECH2"
        }
      ],
      "nameservers": [
        {
          "hostname": "ns.kraxnet.cz",
          "addresses": [
            {
              "ip": "1.2.3.4"
            }
          ]
        },
        {
          "hostname": "ns.kraxnet.com",
          "addresses": [
            {
              "ip": "5.6.7.8"
            },
            {
              "ip": "9.10.11.12"
            }
          ]
        }
      ],
      "authorization_key": "1234abcd",
      "report_level": "7"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190975,
    "registry_object_name": "NSSET",
    "object_type": "nsset",
    "content": {
      "techs": [
        {
          "id": "TECH1"
        },
        {
          "id": "TECH2"
        }
      ],
      "nameservers": [
        {
          "hostname": "ns.kraxnet.cz",
          "addresses": [
            {
              "ip": "1.2.3.4"
            }
          ]
        },
        {
          "hostname": "ns.kraxnet.com",
          "addresses": [
            {
              "ip": "5.6.7.8"
            },
            {
              "ip": "9.10.11.12"
            }
          ]
        }
      ],
      "authorization_key": "1234abcd",
      "report_level": "7"
    },
    "status": "processing",
    "request_type": "register"
  }
}

Služba pro aktualizaci nssetu.

Parametry:

* **id** - identifikátor nssetu
* **nameservers** - výčet nameserverů
* **techs** - identifikátory kontaktů oprávněných ke správě nssetu
* **authorization_key** - autorizační klíč NSSETu
* **report_level** - úroveň kontroly

POST /nssets/update
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "nssets": [
    {
      "id": "NSSET",
      "techs": [
        {
          "id": "TECH1"
        },
        {
          "id": "TECH2"
        }
      ],
      "nameservers": [
        {
          "hostname": "ns.kraxnet.cz",
          "addresses": [
            {
              "ip": "1.2.3.4"
            }
          ]
        },
        {
          "hostname": "ns.kraxnet.cz",
          "addresses": [
            {
              "ip": "5.6.7.8"
            },
            {
              "ip": "9.10.11.12"
            }
          ]
        }
      ],
      "authorization_key": "1234abcd",
      "report_level": "7"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190976,
    "registry_object_name": "NSSET",
    "object_type": "nsset",
    "content": {
      "techs": [
        {
          "id": "TECH1"
        },
        {
          "id": "TECH2"
        }
      ],
      "nameservers": [
        {
          "hostname": "ns.kraxnet.cz",
          "addresses": [
            {
              "ip": "1.2.3.4"
            }
          ]
        },
        {
          "hostname": "ns.kraxnet.cz",
          "addresses": [
            {
              "ip": "5.6.7.8"
            },
            {
              "ip": "9.10.11.12"
            }
          ]
        }
      ],
      "authorization_key": "1234abcd",
      "report_level": "7"
    },
    "status": "processing",
    "request_type": "update"
  }
}

Služba pro zrušení nssetu. Pouze pokud není navázán na doménu.

Parametry:

* **id** - identifikátor nssetu

POST /nssets/delete
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "nssets": [
    {
      "id": "NSSET"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190977,
    "registry_object_name": "NSSET",
    "object_type": "nsset",
    "content": null,
    "status": "waiting_for_authorization",
    "request_type": "delete"
  }
}

--
Requests
Tato část popisuje práci s odpověďmi na požadavky
--

Služba pro zjištění aktuálního stavu požadavku.

Parametry:

* **id** - identifikátor požadavku

Hodnoty odpovědi:

* **processing** - požadavek je ve zpracování
* **failed** - požadavek nebyl zpracován kvůli chybě
* **registered** - (pouze pro požadavek na registraci domény, kontaktu, nssetu) - objekt úspěšně zaregistrován
* **transferred** - (pouze pro požadavek na transfer domény, kontaktu, nssetu) - objekt úspěšně převeden
* **available** - (pouze pro požadavek na ověření dostupnosti domény, kontaktu, nssetu) - objekt je volný pro novou registraci
* **unavailable** - (pouze pro požadavek na ověření dostupnosti domény, kontaktu, nssetu) - objekt není volný
* **successful** - požadavek byl úspěšně zpracován

GET /requests/{id}/status
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190979,
    "status": "available",
    "message": "Domain is available"
  }
}

Služba pro získání všech odpovědí na zaslaný požadavek.

Parametry:

* **id** - identifikátor požadavku

GET /requests/{id}/responses
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "responses": [
    {
      "id": 980190969,
      "code": 200,
      "status": "Domain is available"
    }
  ]
}

Služba pro získání obsahu odeslaného požadavku.

Parametry:

* **id** - identifikátor požadavku

GET /requests/{id}
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "request": {
    "id": 980190981,
    "registry_object_name": "domena.cz",
    "object_type": "domain",
    "content": null,
    "status": "successful",
    "request_type": "check"
  }
}

--
Account
Tato část popisuje práci se subregistrátorským účtem
--

Zjištění aktuálního stavu kreditu.

GET /account/balance
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
< 200
< Content-Type: application/json; charset=utf-8
{
  "balance": {
    "currency": "CZK",
    "amount": 0.0
  }
}

--
Order
Tato část popisuje zadávání objednávek s více požadavky
--

Služba pro zadání objednávky s více požadavky naráz.

Základní parametry jednotlivých požadavků:

* **request_type** - typ požadavku
* **object_type** - typ objektu, kterého se požadavek týká
* **name** - název objektu, které se požadavek týká (pouze pro domény)
* **id** - identifikátor objektu, kterého se požadavek týká (pro ostatní objekty)

Další parametry jsou shodné jako u příslušného typu requestu - viz výše.

Povolené hodnoty **object_type**:

* domain
* contact
* nsset
* keyset

Povolené hodnoty **request_type**:

* check
* register
* update
* authinfo
* transfer

Pro domény navíc:

* renew
* change_dns
* registrant_change

Pro ostatní objekty navíc:

* delete

POST /orders
> Content-Type: application/json
> Accept: application/vnd.1x.common_v1+json
{
  "requests": [
    {
      "request_type": "check",
      "object_type": "domain",
      "name": "domena.cz"
    },
    {
      "request_type": "check",
      "object_type": "domain",
      "name": "domena2.cz"
    }
  ]
}
< 202
< Content-Type: application/json; charset=utf-8
{
  "order": {
    "id": 980190982,
    "created_at": "2014-10-21T21:57:41+02:00",
    "requests": [
      {
        "id": 980190982,
        "registry_object_name": "domena.cz",
        "object_type": "domain",
        "content": null,
        "status": "processing",
        "request_type": "check"
      },
      {
        "id": 980190983,
        "registry_object_name": "domena2.cz",
        "object_type": "domain",
        "content": null,
        "status": "processing",
        "request_type": "check"
      }
    ],
    "_links": {
      "self": {
        "href": "/multi_requests/980190982"
      }
    }
  }
}
